// One version number, in one place, bumped once per build.
//
// package.json holds it. This script raises the build number, then writes it
// into src/version.ts so the interface can show it. Nothing else records a
// version: if you want to know what a build is, read the bottom of the page.
//
// Called by `npm run build` as the first command in the chain, deliberately not
// as a `prebuild` lifecycle hook: this machine has npm's ignore-scripts set to
// true, which skips every hook silently. A version that silently stops being
// stamped is how a build gets misidentified in the first place.

import { readFile, writeFile } from 'node:fs/promises'

const pkgPath = new URL('../package.json', import.meta.url)
const outPath = new URL('../src/version.ts', import.meta.url)

const pkg = JSON.parse(await readFile(pkgPath, 'utf8'))

const parts = pkg.version.split('.')
if (parts.length !== 3 || parts.some((p) => !/^\d+$/.test(p))) {
  throw new Error(`package.json version must be three numbers, got "${pkg.version}"`)
}

const [major, line, build] = parts.map(Number)
const version = `${major}.${line}.${build + 1}`

pkg.version = version
await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n')

await writeFile(outPath, `// Generated by scripts/stamp-version.mjs on every build. Do not edit.
export const VERSION = '${version}'
`)

console.log(`version ${version}`)
